# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  # Build our site
  - binaries/hugo --theme=fresh
  # Create a CNAME file which maps our site to our custom domain
  - cd public
  - echo freshswift.net >> CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  # Our token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
