# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

# Clean and don't fail
install:
  - rm -rf docs || exit 0

# Build the website
script:
  - binaries/hugo --theme=beautifulhugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
